import Head from "next/head";

// import ManualHeader from "../components/ManualHeader";
import Header from "../components/Header";
import CandyCrush from "../components/CandyCrush";
import LotteryEntrance from "../components/LotteryEntrance";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Smart Contract Lottery</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <ManualHeader /> */}
			<Header />
			{/* <Timer /> */}
			<LotteryEntrance />
			<CandyCrush />
			{/* <div>sup</div> */}
		</div>
	);
}
